In [1]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000]
}

df = pd.DataFrame(data)

In [2]:
df

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [4]:
df.loc[df['City'].str.contains("New")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [6]:
df.loc[df['City'].str.contains("new", case=False)]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [8]:
# start with los

df.loc[df['City'].str.contains(r"^Los")]

  Name         City Department  Salary
1  Bob  Los Angeles         IT   60000

In [9]:
# end with rk

df.loc[df['City'].str.contains(r"rk$")]

      Name      City Department  Salary
0    Alice  New York         HR   50000
2  Charlie    Newark    Finance   55000

In [11]:
# name star with a vowel

df.loc[df['Name'].str.contains(r"^[AEIOU]")]

    Name       City Department  Salary
0  Alice   New York         HR   50000
4    Eve  New Delhi         HR   52000

In [12]:
# string contains New or Los

df.loc[df['City'].str.contains(r"New|Los")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000
8    Sakib    H Los Ang         HR   70000

In [13]:
df = pd.read_csv('student_data.csv')
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [14]:
# adding a column with constant value

df['Country'] = 'Bangladesh'
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh